#!/usr/bin/env python3
"""Golden vectors for the two RDF 1.2 term encodings (RECORD-T-0022).

Derived from the documents alone — architecture.md par. 3.2 (the canonical
encoding and its injectivity argument), par. 11.3 (the triple-term layout) and
RECORD-A-0007 (the base-direction layout) — and deliberately *not* by running
the Odin encoder. A golden vector generated by the implementation proves only
that the implementation is deterministic; RECORD-T-0001 established the method
and RECORD-T-0006 is the reason it is kept.

Every constant below cites the section that fixes it. Run with no arguments to
print the vectors as Odin string literals for record/intern_test.odin.
"""

# architecture.md par. 3.2, extended by par. 11.3 and RECORD-A-0007.
TAG_IRI = 0x01
TAG_BLANK = 0x02
TAG_STRING = 0x03
TAG_LANG = 0x04
TAG_TYPED = 0x05
TAG_SPLIT_IRI = 0x06  # par. 3.5
TAG_TRIPLE = 0x07  # par. 11.3
TAG_DIR_LANG = 0x08  # RECORD-A-0007

# rdf.Direction (odin-rdf-parser, rdf/terms.odin): None = 0, LTR = 1, RTL = 2.
# 0 never appears under TAG_DIR_LANG — a direction-less literal is TAG_LANG,
# and admitting both would be two encodings of one term.
DIR_LTR = 1
DIR_RTL = 2


def u64(v: int) -> bytes:
    """par. 3.2: dictionary references are 8-byte big-endian."""
    assert 0 <= v < 1 << 64
    return v.to_bytes(8, "big")


def iri(value: str) -> bytes:
    return bytes([TAG_IRI]) + value.encode()


def lang(language: str, lexical: str) -> bytes:
    """par. 3.2: len(tag) u8 | lowercased BCP-47 tag | lexical form."""
    tag = language.lower().encode()
    assert 0 < len(tag) <= 255, "par. 3.2 rejects tags over 255 bytes"
    return bytes([TAG_LANG, len(tag)]) + tag + lexical.encode()


def dir_lang(language: str, direction: int, lexical: str) -> bytes:
    """RECORD-A-0007: tag | langlen u8 | dir u8 | lang | lexical.

    The same lowercase fold as TAG_LANG, or the two tags disagree about
    term identity for the language half. Three refusals keep it injective
    and are asserted here rather than encoded around.
    """
    tag = language.lower().encode()
    assert len(tag) > 0, "a dirLangString always carries a language"
    assert len(tag) <= 255, "par. 3.2's length byte"
    assert direction in (DIR_LTR, DIR_RTL), "None is TAG_LANG; nothing else is a direction"
    return bytes([TAG_DIR_LANG, len(tag), direction]) + tag + lexical.encode()


def triple(s: int, p: int, o: int) -> bytes:
    """par. 11.3: 0x07 | sID | pID | oID — three ids, 25 bytes, fixed length.

    The ids are *on-disk* ids (RECORD-A-0008 decision 3): the log's own id
    space, so an inlined component carries par. 3.4's bit-63 form and not the
    resident re-tagging.
    """
    for component in (s, p, o):
        assert component != 0, "0 is 'none', never a term"
    enc = bytes([TAG_TRIPLE]) + u64(s) + u64(p) + u64(o)
    assert len(enc) == 25
    return enc


# par. 3.4: bit 63 set, tag in 62..56, payload biased by 2^55.
INLINE_FLAG = 1 << 63
INLINE_TAG_INTEGER = 0x02 << 56
INLINE_BIAS = 1 << 55


def inline_integer(v: int) -> int:
    return INLINE_FLAG | INLINE_TAG_INTEGER | (v + INLINE_BIAS)


def odin_literal(raw: bytes) -> str:
    """The bytes as an Odin string literal, printable ASCII kept readable."""
    out = []
    for b in raw:
        if 0x20 <= b < 0x7F and b not in (0x22, 0x5C):
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return '"' + "".join(out) + '"'


VECTORS = [
    # A triple term over three dictionary ids: the shape every reifying
    # triple in the W3C rdf12 corpus produces once its parts are interned.
    ("triple over dictionary ids (1, 2, 3)", triple(1, 2, 3)),
    # A component that is an inlined literal — the case that makes the
    # disk-vs-resident id question real (RECORD-A-0008 decision 3).
    ("triple whose object is the inlined integer 5", triple(1, 2, inline_integer(5))),
    # Nesting: construct-3.ttl carries << _:r rdf:reifies <<( :a :b :c )>> >>,
    # so the inner triple term is interned first and is component 3 here.
    ("triple whose object is the triple term with id 9", triple(4, 5, 9)),
    ("dir-lang, ltr", dir_lang("en", DIR_LTR, "Alice")),
    ("dir-lang, rtl", dir_lang("ar", DIR_RTL, "مرحبا")),
    # The fold, which must match TAG_LANG's or term identity forks.
    ("dir-lang, tag folded to lowercase", dir_lang("EN-NZ", DIR_LTR, "Alice")),
    # For the injectivity test's converse half: these two must differ.
    ("lang, no direction (TAG_LANG, not TAG_DIR_LANG)", lang("en", "Alice")),
]

if __name__ == "__main__":
    for name, raw in VECTORS:
        print(f"{name:52} {len(raw):3}B  {odin_literal(raw)}")
